"""
Python source code parser.

Walks a Python codebase using the ast module and produces a CodeGraph
with nodes (modules, classes, functions) and edges (calls, imports,
inheritance, containment).

Call graph generation is delegated to PyCG (vendored), which performs
inter-procedural analysis with assignment tracking to resolve calls
including obj.method(), cross-module imports, and closures.
"""

from __future__ import annotations

import ast
import logging
import os
from pathlib import Path

from topo_parser.ast_resolve import (
    _resolve_call_edges_ast,
    _resolve_inherits_edges,
    _resolve_name,
    _try_resolve,
)
from topo_parser.graph import CodeGraph, Edge, EdgeKind, Node, NodeKind

logger = logging.getLogger(__name__)


def parse_python_project(
    root: Path,
    exclude_patterns: list[str] | None = None,
    include_roots: list[Path] | None = None,
) -> CodeGraph:
    """
    Parse a Python project directory into a CodeGraph.

    Walks all .py files under `root`, extracts entities and relationships.
    Detects src-layout packages and uses the Python package root for module IDs.
    Call edges are generated by PyCG's inter-procedural analysis.

    Args:
        root: Path to project directory.
        exclude_patterns: Directory/file name patterns to exclude (e.g. ["pycg", ".venv"]).
            Any .py file whose path contains a matching component is skipped.
        include_roots: Optional sub-roots to include instead of walking the full tree.
    """
    graph = CodeGraph()
    root = root.resolve()
    py_files = _discover_python_files(root, include_roots)

    if exclude_patterns:
        py_files = [
            f for f in py_files
            if not any(pat in f.relative_to(root).parts for pat in exclude_patterns)
        ]

    # Detect Python package roots: directories containing __init__.py that
    # aren't nested inside another package. Handles both flat layout
    # (root/pkg/__init__.py) and src layout (root/src/pkg/__init__.py).
    package_roots = _find_package_roots(root, py_files)

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        _extract_from_file(graph, tree, py_file, pkg_root or root)

    # Use PyCG for call edges (inter-procedural analysis with type inference),
    # falling back to AST-based resolution if PyCG fails.
    pycg_calls = _extract_calls_pycg(root, py_files, package_roots)
    if pycg_calls is not None:
        _add_pycg_calls(graph, pycg_calls)
        # PyCG doesn't resolve super().method() — supplement with AST
        _add_super_calls_ast(graph, root, py_files, package_roots)
    else:
        _resolve_call_edges_ast(graph)

    # Resolve INHERITS edges (always AST-based)
    _resolve_inherits_edges(graph)
    return graph


def _discover_python_files(root: Path, include_roots: list[Path] | None) -> list[Path]:
    """Collect Python files from the requested roots."""
    if not include_roots:
        return sorted(root.rglob("*.py"))

    py_files: list[Path] = []
    seen: set[Path] = set()
    for include_root in include_roots:
        resolved_root = include_root.resolve()
        if not resolved_root.exists():
            continue
        for py_file in resolved_root.rglob("*.py"):
            resolved_file = py_file.resolve()
            if resolved_file not in seen:
                seen.add(resolved_file)
                py_files.append(resolved_file)
    return sorted(py_files)


def _find_package_roots(root: Path, py_files: list[Path]) -> list[Path]:
    """Find directories that serve as Python package roots.

    A package root is the parent of a top-level Python package. For example,
    in a src layout (proj/src/pkg/__init__.py), the package root is proj/src/.
    In a flat layout (proj/pkg/__init__.py), the package root is proj/.
    """
    # Find all directories containing __init__.py
    init_dirs: set[Path] = set()
    for f in py_files:
        if f.name == "__init__.py":
            init_dirs.add(f.parent.resolve())

    # A package root is the parent of a package dir whose parent is NOT itself a package.
    # This gives us the directory from which Python module IDs should be computed.
    package_roots: set[Path] = set()
    for pkg_dir in init_dirs:
        parent = pkg_dir.parent
        if parent not in init_dirs:
            package_roots.add(parent)

    return sorted(package_roots)


def _best_package_root(file: Path, package_roots: list[Path]) -> Path | None:
    """Find the most specific package root that contains this file."""
    file = file.resolve()
    best: Path | None = None
    for pr in package_roots:
        if file.is_relative_to(pr):
            if best is None or len(pr.parts) > len(best.parts):
                best = pr
    return best


def _module_id(file: Path, root: Path) -> str:
    """Derive a module id from file path relative to root."""
    rel = file.relative_to(root)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts) if parts else rel.stem


def _extract_from_file(
    graph: CodeGraph, tree: ast.Module, file: Path, root: Path
) -> None:
    """Extract nodes and edges from a single parsed file."""
    mod_id = _module_id(file, root)

    # Module node
    graph.add_node(Node(id=mod_id, kind=NodeKind.MODULE, file=file, line=1, name=mod_id.split(".")[-1]))

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            _extract_class(graph, node, mod_id, file)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, node, mod_id, file)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            _extract_import(graph, node, mod_id)


def _extract_class(
    graph: CodeGraph, node: ast.ClassDef, parent_id: str, file: Path
) -> None:
    """Extract a class node, its methods, and inheritance edges."""
    class_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=class_id, kind=NodeKind.CLASS, file=file, line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=class_id, kind=EdgeKind.CONTAINS))

    # Inheritance (raw names, resolved later by _resolve_inherits_edges)
    for base in node.bases:
        base_name = _resolve_name(base)
        if base_name:
            graph.add_edge(Edge(source=class_id, target=base_name, kind=EdgeKind.INHERITS))

    # Methods
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, child, class_id, file)


def _extract_function(
    graph: CodeGraph,
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    parent_id: str,
    file: Path,
) -> None:
    """Extract a function/method node. Call edges are added by PyCG."""
    func_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=func_id, kind=NodeKind.FUNCTION, file=file, line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=func_id, kind=EdgeKind.CONTAINS))


def _extract_import(graph: CodeGraph, node: ast.Import | ast.ImportFrom, mod_id: str) -> None:
    """Extract import edges.

    For `import foo.bar`, creates an edge to `foo.bar`.
    For `from foo.bar import baz, qux`, creates edges to both
    `foo.bar` (the module) and `foo.bar.baz`, `foo.bar.qux` (the names).
    This allows call resolution to map `baz()` -> `foo.bar.baz`.
    """
    if isinstance(node, ast.Import):
        for alias in node.names:
            graph.add_edge(Edge(source=mod_id, target=alias.name, kind=EdgeKind.IMPORTS))
    elif node.module:
        graph.add_edge(Edge(source=mod_id, target=node.module, kind=EdgeKind.IMPORTS))
        for alias in node.names:
            if alias.name != "*":
                qualified = f"{node.module}.{alias.name}"
                graph.add_edge(Edge(source=mod_id, target=qualified, kind=EdgeKind.IMPORTS))


## ---------------------------------------------------------------------------
## PyCG integration — inter-procedural call graph generation
## ---------------------------------------------------------------------------


def _extract_calls_pycg(
    root: Path, py_files: list[Path], package_roots: list[Path],
) -> dict[str, list[str]] | None:
    """Run PyCG on the project and return the call graph as {caller: [callees]}.

    Returns None if PyCG fails (the caller should fall back to AST resolution).

    For monorepos with multiple package roots, PyCG is run once per package root
    so that each package's imports resolve correctly.
    """
    try:
        from pycg.pycg import CallGraphGenerator
    except ImportError:
        logger.debug("PyCG not available, falling back to AST resolution")
        return None

    if not py_files:
        return None

    # Group files by their package root so PyCG can resolve imports correctly.
    groups: list[tuple[str, list[str]]] = []
    if package_roots:
        for pkg_root in package_roots:
            files_in_root = [str(f) for f in py_files if f.is_relative_to(pkg_root)]
            if files_in_root:
                groups.append((str(pkg_root), files_in_root))
    if not groups:
        # Fallback: use project root for all files
        groups.append((str(root), [str(f) for f in py_files]))

    merged: dict[str, list[str]] = {}
    old_cwd = os.getcwd()
    try:
        for pkg_dir, entry_points in groups:
            os.chdir(str(root))
            try:
                cg = CallGraphGenerator(entry_points, pkg_dir, -1, "call-graph")
                cg.analyze()
                raw = cg.output()
                for caller, callees in raw.items():
                    callee_list = sorted(callees) if isinstance(callees, set) else list(callees)
                    merged.setdefault(caller, []).extend(callee_list)
            except Exception:
                logger.debug("PyCG analysis failed for %s", pkg_dir, exc_info=True)
                continue
        return merged if merged else None
    finally:
        os.chdir(old_cwd)


def _add_pycg_calls(graph: CodeGraph, pycg_calls: dict[str, list[str]]) -> None:
    """Add CALLS edges from PyCG output, mapping to known graph nodes.

    PyCG produces fully-qualified names like 'pkg.module.Class.method'.
    When PyCG can't resolve a package, it may produce path-based names like
    'path.to.src.pkg.module.func'. We try suffix matching to recover these.
    Only edges where both source and target are known nodes are added.
    """
    node_ids = set(graph.nodes)

    # Build suffix index for fuzzy matching: for each node ID, index all
    # suffixes (e.g. "pkg.mod.func" indexes "pkg.mod.func", "mod.func", "func")
    suffix_to_node: dict[str, str | None] = {}
    for nid in node_ids:
        parts = nid.split(".")
        for i in range(len(parts)):
            suffix = ".".join(parts[i:])
            if suffix in suffix_to_node:
                # Ambiguous suffix — mark as unusable
                suffix_to_node[suffix] = None
            else:
                suffix_to_node[suffix] = nid

    def _resolve_pycg_id(pycg_id: str) -> str | None:
        """Match a PyCG identifier to a graph node ID."""
        if pycg_id in node_ids:
            return pycg_id
        # Try progressively shorter suffixes of the PyCG ID
        parts = pycg_id.split(".")
        for i in range(len(parts)):
            suffix = ".".join(parts[i:])
            match = suffix_to_node.get(suffix)
            if match is not None:
                return match
        return None

    seen: set[tuple[str, str]] = set()
    for caller, callees in pycg_calls.items():
        source = _resolve_pycg_id(caller)
        if source is None:
            continue
        for callee in callees:
            target = _resolve_pycg_id(callee)
            if target is None:
                continue
            edge_key = (source, target)
            if edge_key not in seen:
                seen.add(edge_key)
                graph.add_edge(Edge(source=source, target=target, kind=EdgeKind.CALLS))


def _add_super_calls_ast(
    graph: CodeGraph, root: Path, py_files: list[Path], package_roots: list[Path],
) -> None:
    """Supplement PyCG with AST-based super().method() resolution.

    PyCG resolves super() to <builtin>.super but doesn't follow through
    to the parent class method. We walk the AST to find super().method()
    patterns and resolve them using the declared base class.
    """
    node_ids = set(graph.nodes)
    existing_calls = {(e.source, e.target) for e in graph.edges_by_kind(EdgeKind.CALLS)}

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        file_root = pkg_root or root
        mod_id = _module_id(py_file, file_root)

        for cls_node in ast.walk(tree):
            if not isinstance(cls_node, ast.ClassDef):
                continue
            class_id = f"{mod_id}.{cls_node.name}"
            if not cls_node.bases:
                continue
            base_name = _resolve_name(cls_node.bases[0])
            if not base_name:
                continue

            for method in ast.iter_child_nodes(cls_node):
                if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                func_id = f"{class_id}.{method.name}"
                if func_id not in node_ids:
                    continue

                for child in ast.walk(method):
                    if not isinstance(child, ast.Call):
                        continue
                    if not (
                        isinstance(child.func, ast.Attribute)
                        and isinstance(child.func.value, ast.Call)
                        and isinstance(child.func.value.func, ast.Name)
                        and child.func.value.func.id == "super"
                    ):
                        continue
                    # super().method_name -> resolve to base class
                    method_name = child.func.attr
                    raw_target = f"{base_name}.{method_name}"
                    # Try to resolve the raw target to a known node
                    target = _try_resolve(func_id, raw_target, node_ids, {})
                    if target and (func_id, target) not in existing_calls:
                        existing_calls.add((func_id, target))
                        graph.add_edge(Edge(
                            source=func_id, target=target, kind=EdgeKind.CALLS,
                        ))


