"""
Python source code parser.

Walks a Python codebase using the ast module and produces a CodeGraph
with nodes (modules, classes, functions) and edges (calls, imports,
inheritance, containment).

Call graph generation is delegated to PyCG (vendored), which performs
inter-procedural analysis with assignment tracking to resolve calls
including obj.method(), cross-module imports, and closures.
"""

from __future__ import annotations

import ast
import logging
import os
from pathlib import Path

from topo_parser.ast_resolve import (
    _resolve_call_edges_ast,
    _resolve_inherits_edges,
    _resolve_name,
    _try_resolve,
)
from topo_parser.graph import CodeGraph, Edge, EdgeKind, Node, NodeKind

logger = logging.getLogger(__name__)


def parse_python_project(
    root: Path,
    exclude_patterns: list[str] | None = None,
    include_roots: list[Path] | None = None,
) -> CodeGraph:
    """
    Parse a Python project directory into a CodeGraph.

    Walks all .py files under `root`, extracts entities and relationships.
    Detects src-layout packages and uses the Python package root for module IDs.
    Call edges are generated by PyCG's inter-procedural analysis.

    Args:
        root: Path to project directory.
        exclude_patterns: Directory/file name patterns to exclude (e.g. ["pycg", ".venv"]).
            Any .py file whose path contains a matching component is skipped.
        include_roots: Optional sub-roots to include instead of walking the full tree.
    """
    graph = CodeGraph()
    root = root.resolve()
    py_files = _discover_python_files(root, include_roots)

    if exclude_patterns:
        py_files = [
            f for f in py_files
            if not any(pat in f.relative_to(root).parts for pat in exclude_patterns)
        ]

    # Detect Python package roots: directories containing __init__.py that
    # aren't nested inside another package. Handles both flat layout
    # (root/pkg/__init__.py) and src layout (root/src/pkg/__init__.py).
    package_roots = _find_package_roots(root, py_files)

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        _extract_from_file(graph, tree, py_file, pkg_root or root)

    # Use PyCG for call edges (inter-procedural analysis with type inference),
    # falling back to AST-based resolution if PyCG fails.
    pycg_calls = _extract_calls_pycg(root, py_files, package_roots)
    if pycg_calls is not None:
        _add_pycg_calls(graph, pycg_calls)
        # PyCG doesn't resolve super().method() — supplement with AST
        _add_super_calls_ast(graph, root, py_files, package_roots)
    else:
        _resolve_call_edges_ast(graph)

    # PyCG doesn't track @property access (it sees attribute access, not
    # function calls).  Supplement with AST-based property resolution.
    _add_property_access_calls(graph, root, py_files, package_roots)

    # Resolve INHERITS edges (always AST-based)
    _resolve_inherits_edges(graph)
    return graph


def _discover_python_files(root: Path, include_roots: list[Path] | None) -> list[Path]:
    """Collect Python files from the requested roots."""
    if not include_roots:
        return sorted(root.rglob("*.py"))

    py_files: list[Path] = []
    seen: set[Path] = set()
    for include_root in include_roots:
        resolved_root = include_root.resolve()
        if not resolved_root.exists():
            continue
        for py_file in resolved_root.rglob("*.py"):
            resolved_file = py_file.resolve()
            if resolved_file not in seen:
                seen.add(resolved_file)
                py_files.append(resolved_file)
    return sorted(py_files)


def _find_package_roots(root: Path, py_files: list[Path]) -> list[Path]:
    """Find directories that serve as Python package roots.

    A package root is the parent of a top-level Python package. For example,
    in a src layout (proj/src/pkg/__init__.py), the package root is proj/src/.
    In a flat layout (proj/pkg/__init__.py), the package root is proj/.
    """
    # Find all directories containing __init__.py
    init_dirs: set[Path] = set()
    for f in py_files:
        if f.name == "__init__.py":
            init_dirs.add(f.parent.resolve())

    # A package root is the parent of a package dir whose parent is NOT itself a package.
    # This gives us the directory from which Python module IDs should be computed.
    package_roots: set[Path] = set()
    for pkg_dir in init_dirs:
        parent = pkg_dir.parent
        if parent not in init_dirs:
            package_roots.add(parent)

    return sorted(package_roots)


def _best_package_root(file: Path, package_roots: list[Path]) -> Path | None:
    """Find the most specific package root that contains this file."""
    file = file.resolve()
    best: Path | None = None
    for pr in package_roots:
        if file.is_relative_to(pr):
            if best is None or len(pr.parts) > len(best.parts):
                best = pr
    return best


def _module_id(file: Path, root: Path) -> str:
    """Derive a module id from file path relative to root."""
    rel = file.relative_to(root)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts) if parts else rel.stem


_STRUCTURAL_STMT_TYPES = (
    ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef,
    ast.Import, ast.ImportFrom,
)


def _extract_from_file(
    graph: CodeGraph, tree: ast.Module, file: Path, root: Path
) -> None:
    """Extract nodes and edges from a single parsed file.

    Files with no structural content (no classes, functions, or imports)
    are skipped — they are namespace markers, not code entities.
    """
    children = list(ast.iter_child_nodes(tree))

    if not any(isinstance(node, _STRUCTURAL_STMT_TYPES) for node in children):
        return  # Namespace-only file (empty, docstring-only, etc.)

    mod_id = _module_id(file, root)
    graph.add_node(Node(id=mod_id, kind=NodeKind.MODULE, file=str(file), line=1, name=mod_id.split(".")[-1]))

    for node in children:
        if isinstance(node, ast.ClassDef):
            _extract_class(graph, node, mod_id, file)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, node, mod_id, file)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            _extract_import(graph, node, mod_id, file)


def _extract_class(
    graph: CodeGraph, node: ast.ClassDef, parent_id: str, file: Path
) -> None:
    """Extract a class node, its methods, and inheritance edges."""
    class_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=class_id, kind=NodeKind.CLASS, file=str(file), line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=class_id, kind=EdgeKind.CONTAINS))

    # Inheritance (raw names, resolved later by _resolve_inherits_edges)
    for base in node.bases:
        base_name = _resolve_name(base)
        if base_name:
            graph.add_edge(Edge(source=class_id, target=base_name, kind=EdgeKind.INHERITS))

    # Methods
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, child, class_id, file)


def _extract_function(
    graph: CodeGraph,
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    parent_id: str,
    file: Path,
) -> None:
    """Extract a function/method node. Call edges are added by PyCG."""
    func_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=func_id, kind=NodeKind.FUNCTION, file=str(file), line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=func_id, kind=EdgeKind.CONTAINS))


def _resolve_relative_import(
    mod_id: str, file: Path, level: int, module: str | None,
) -> str | None:
    """Resolve a relative import to a fully-qualified module path.

    Args:
        mod_id: Fully-qualified ID of the importing module.
        file: Path to the importing file (needed to detect __init__.py).
        level: Number of dots in the relative import (1 = current package).
        module: The module part of ``from .module import name`` (may be None).

    Returns:
        Fully-qualified module path, or None if the import goes above the root.
    """
    if file.name == "__init__.py":
        package_parts = mod_id.split(".")
    else:
        package_parts = mod_id.rsplit(".", 1)[0].split(".") if "." in mod_id else []

    levels_up = level - 1
    if levels_up >= len(package_parts):
        return None
    if levels_up > 0:
        package_parts = package_parts[:-levels_up]

    base = ".".join(package_parts)
    if module:
        return f"{base}.{module}" if base else module
    return base or None


def _extract_import(
    graph: CodeGraph, node: ast.Import | ast.ImportFrom, mod_id: str, file: Path,
) -> None:
    """Extract import edges with fully-qualified targets.

    For ``import foo.bar``, creates an edge to ``foo.bar``.
    For ``from foo.bar import baz``, creates edges to ``foo.bar`` and ``foo.bar.baz``.
    For relative imports (``from .foo import bar``), resolves the target using
    the importing module's position in the package hierarchy.
    """
    if isinstance(node, ast.Import):
        for alias in node.names:
            graph.add_edge(Edge(source=mod_id, target=alias.name, kind=EdgeKind.IMPORTS))
        return

    if isinstance(node, ast.ImportFrom) and node.level > 0:
        base = _resolve_relative_import(mod_id, file, node.level, node.module)
    elif node.module:
        base = node.module
    else:
        return

    if base is None:
        return

    graph.add_edge(Edge(source=mod_id, target=base, kind=EdgeKind.IMPORTS))
    for alias in node.names:
        if alias.name != "*":
            graph.add_edge(Edge(source=mod_id, target=f"{base}.{alias.name}", kind=EdgeKind.IMPORTS))


## ---------------------------------------------------------------------------
## PyCG integration — inter-procedural call graph generation
## ---------------------------------------------------------------------------


_PYCG_MAX_ITER = 3
"""Cap PyCG's fixpoint iterations.

PyCG's inter-procedural analysis iterates until its assignment state
converges.  For codebases with deep class hierarchies (e.g. Click's 4-level
inheritance chains), the state grows each iteration and convergence never
happens — each round discovers more transitive call targets, exponentially
increasing both state size and per-iteration cost.

Empirically, Flask converges at iteration 3 and Click's state explodes
after iteration 3.  Capping at 3 gives correct results for well-behaved
codebases while preventing unbounded runtime on adversarial ones.
"""

_PYCG_TIMEOUT_SECONDS = 30
"""Hard timeout per package root for PyCG analysis.

Safety net in case max_iter alone isn't sufficient to prevent hangs.
"""


def _extract_calls_pycg(
    root: Path, py_files: list[Path], package_roots: list[Path],
) -> dict[str, list[str]] | None:
    """Run PyCG on the project and return the call graph as {caller: [callees]}.

    Returns None if PyCG fails (the caller should fall back to AST resolution).

    For monorepos with multiple package roots, PyCG is run once per package root
    so that each package's imports resolve correctly.
    """
    try:
        from pycg.pycg import CallGraphGenerator
    except ImportError:
        logger.debug("PyCG not available, falling back to AST resolution")
        return None

    if not py_files:
        return None

    # Group files by their package root so PyCG can resolve imports correctly.
    groups: list[tuple[str, list[str]]] = []
    if package_roots:
        for pkg_root in package_roots:
            files_in_root = [str(f) for f in py_files if f.is_relative_to(pkg_root)]
            if files_in_root:
                groups.append((str(pkg_root), files_in_root))
    if not groups:
        # Fallback: use project root for all files
        groups.append((str(root), [str(f) for f in py_files]))

    merged: dict[str, list[str]] = {}
    old_cwd = os.getcwd()
    try:
        for pkg_dir, entry_points in groups:
            os.chdir(str(root))
            try:
                cg = CallGraphGenerator(
                    entry_points, pkg_dir, _PYCG_MAX_ITER, "call-graph",
                )
                cg.analyze()
                raw = cg.output()
                for caller, callees in raw.items():
                    callee_list = sorted(callees) if isinstance(callees, set) else list(callees)
                    merged.setdefault(caller, []).extend(callee_list)
            except Exception:
                logger.debug("PyCG analysis failed for %s", pkg_dir, exc_info=True)
                continue
        return merged if merged else None
    finally:
        os.chdir(old_cwd)


def _add_pycg_calls(graph: CodeGraph, pycg_calls: dict[str, list[str]]) -> None:
    """Add CALLS edges from PyCG output, mapping to known graph nodes.

    PyCG produces fully-qualified names like 'pkg.module.Class.method'.
    When PyCG can't resolve a package, it may produce path-based names like
    'path.to.src.pkg.module.func'. We try suffix matching to recover these.
    Only edges where both source and target are known nodes are added.

    Cross-module call edges are validated against the import graph: a call
    from module A to something in module B is only kept if A has an import
    edge targeting B or one of B's members. This eliminates phantom edges
    from ambiguous suffix matching.
    """
    node_ids = set(graph.nodes)
    module_ids = {nid for nid, node in graph.nodes.items() if node.kind == NodeKind.MODULE}

    # Build suffix index for fuzzy matching: for each node ID, index all
    # suffixes (e.g. "pkg.mod.func" indexes "pkg.mod.func", "mod.func", "func")
    suffix_to_node: dict[str, str | None] = {}
    for nid in node_ids:
        parts = nid.split(".")
        for i in range(len(parts)):
            suffix = ".".join(parts[i:])
            if suffix in suffix_to_node:
                # Ambiguous suffix — mark as unusable
                suffix_to_node[suffix] = None
            else:
                suffix_to_node[suffix] = nid

    # Build import targets per module for cross-module call validation.
    import_targets: dict[str, set[str]] = {}
    for edge in graph.edges_by_kind(EdgeKind.IMPORTS):
        src_mod = _module_of(edge.source, module_ids)
        import_targets.setdefault(src_mod, set()).add(edge.target)

    def _resolve_pycg_id(pycg_id: str) -> str | None:
        """Match a PyCG identifier to a graph node ID."""
        if pycg_id in node_ids:
            return pycg_id
        # Try progressively shorter suffixes of the PyCG ID
        parts = pycg_id.split(".")
        for i in range(len(parts)):
            suffix = ".".join(parts[i:])
            match = suffix_to_node.get(suffix)
            if match is not None:
                return match
        return None

    def _has_import_path(source: str, target: str) -> bool:
        """Check that source's module imports target's module (or an ancestor)."""
        src_mod = _module_of(source, module_ids)
        tgt_mod = _module_of(target, module_ids)
        if src_mod == tgt_mod:
            return True
        targets = import_targets.get(src_mod, set())
        # Check if any prefix of the target is an import target
        tgt_parts = target.split(".")
        return any(
            ".".join(tgt_parts[:i]) in targets
            for i in range(1, len(tgt_parts) + 1)
        )

    seen: set[tuple[str, str]] = set()
    for caller, callees in pycg_calls.items():
        source = _resolve_pycg_id(caller)
        if source is None:
            continue
        for callee in callees:
            target = _resolve_pycg_id(callee)
            if target is None:
                continue
            edge_key = (source, target)
            if edge_key not in seen and _has_import_path(source, target):
                seen.add(edge_key)
                graph.add_edge(Edge(source=source, target=target, kind=EdgeKind.CALLS))


def _module_of(node_id: str, module_ids: set[str]) -> str:
    """Find the owning module of a node by walking up its dotted name."""
    if node_id in module_ids:
        return node_id
    parts = node_id.split(".")
    for i in range(len(parts) - 1, 0, -1):
        candidate = ".".join(parts[:i])
        if candidate in module_ids:
            return candidate
    return parts[0]


def _add_super_calls_ast(
    graph: CodeGraph, root: Path, py_files: list[Path], package_roots: list[Path],
) -> None:
    """Supplement PyCG with AST-based super().method() resolution.

    PyCG resolves super() to <builtin>.super but doesn't follow through
    to the parent class method. We walk the AST to find super().method()
    patterns and resolve them using the declared base class.
    """
    node_ids = set(graph.nodes)
    existing_calls = {(e.source, e.target) for e in graph.edges_by_kind(EdgeKind.CALLS)}

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        file_root = pkg_root or root
        mod_id = _module_id(py_file, file_root)

        for cls_node in ast.walk(tree):
            if not isinstance(cls_node, ast.ClassDef):
                continue
            class_id = f"{mod_id}.{cls_node.name}"
            if not cls_node.bases:
                continue
            base_name = _resolve_name(cls_node.bases[0])
            if not base_name:
                continue

            for method in ast.iter_child_nodes(cls_node):
                if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                func_id = f"{class_id}.{method.name}"
                if func_id not in node_ids:
                    continue

                for child in ast.walk(method):
                    if not isinstance(child, ast.Call):
                        continue
                    if not (
                        isinstance(child.func, ast.Attribute)
                        and isinstance(child.func.value, ast.Call)
                        and isinstance(child.func.value.func, ast.Name)
                        and child.func.value.func.id == "super"
                    ):
                        continue
                    # super().method_name -> resolve to base class
                    method_name = child.func.attr
                    raw_target = f"{base_name}.{method_name}"
                    # Try to resolve the raw target to a known node
                    target = _try_resolve(func_id, raw_target, node_ids, {})
                    if target and (func_id, target) not in existing_calls:
                        existing_calls.add((func_id, target))
                        graph.add_edge(Edge(
                            source=func_id, target=target, kind=EdgeKind.CALLS,
                        ))


def _add_property_access_calls(
    graph: CodeGraph, root: Path, py_files: list[Path], package_roots: list[Path],
) -> None:
    """Add CALLS edges for @property access that PyCG misses.

    PyCG treats ``obj.prop`` as attribute access, not a function call, so
    @property methods never get CALLS edges.  This walks the AST to find
    attribute accesses that target known @property methods, using lightweight
    type inference (constructor assignment and parameter annotations) to
    determine the class.
    """
    node_ids = set(graph.nodes)
    module_ids = {nid for nid, n in graph.nodes.items() if n.kind == NodeKind.MODULE}

    # Step 1: Collect @property methods per class.
    # property_map: {attr_name: [(class_id, method_node_id), ...]}
    property_map: dict[str, list[tuple[str, str]]] = {}
    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        file_root = pkg_root or root
        mod_id = _module_id(py_file, file_root)

        for node in ast.walk(tree):
            if not isinstance(node, ast.ClassDef):
                continue
            class_id = f"{mod_id}.{node.name}"
            if class_id not in node_ids:
                continue
            for child in ast.iter_child_nodes(node):
                if not isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                if not any(
                    isinstance(d, ast.Name) and d.id == "property"
                    for d in child.decorator_list
                ):
                    continue
                method_id = f"{class_id}.{child.name}"
                if method_id in node_ids:
                    property_map.setdefault(child.name, []).append(
                        (class_id, method_id)
                    )

    if not property_map:
        return

    # Build a quick lookup: short class name -> set of class_ids
    class_short_to_ids: dict[str, set[str]] = {}
    for nid, n in graph.nodes.items():
        if n.kind == NodeKind.CLASS:
            class_short_to_ids.setdefault(n.name, set()).add(nid)

    # Build import targets per module for validation.
    import_targets: dict[str, set[str]] = {}
    for edge in graph.edges_by_kind(EdgeKind.IMPORTS):
        src_mod = _module_of(edge.source, module_ids)
        import_targets.setdefault(src_mod, set()).add(edge.target)

    existing_calls = {(e.source, e.target) for e in graph.edges_by_kind(EdgeKind.CALLS)}

    # Step 2: Walk every function, infer local variable types, match property access.
    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        file_root = pkg_root or root
        mod_id = _module_id(py_file, file_root)

        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            # Determine the enclosing scope (module or class.method)
            func_id = _find_func_id(tree, node, mod_id)
            if func_id is None or func_id not in node_ids:
                continue

            # Infer variable types from assignments and annotations.
            # var_types: {variable_name: class_short_name}
            var_types = _infer_variable_types(node)

            # Scan for attribute accesses matching known @property names.
            src_mod = _module_of(func_id, module_ids)
            for child in ast.walk(node):
                if not isinstance(child, ast.Attribute):
                    continue
                attr_name = child.attr
                if attr_name not in property_map:
                    continue
                # Determine the variable being accessed
                if not isinstance(child.value, ast.Name):
                    continue
                var_name = child.value.id
                if var_name in ("self", "cls"):
                    continue  # self.prop is already within the class

                class_name = var_types.get(var_name)
                candidates = property_map[attr_name]

                if class_name is not None:
                    # Type is known — match against the specific class.
                    matched = [
                        (cid, mid) for cid, mid in candidates
                        if cid.rsplit(".", 1)[-1] == class_name
                    ]
                else:
                    # Type is unknown (loop variable, etc.).  Use
                    # import-validated candidates — if exactly one
                    # candidate's class is imported, use it.
                    matched = _import_validated_candidates(
                        candidates, src_mod, module_ids, import_targets,
                    )

                for class_id, method_id in matched:
                    tgt_mod = _module_of(method_id, module_ids)
                    if src_mod != tgt_mod:
                        targets = import_targets.get(src_mod, set())
                        tgt_parts = class_id.split(".")
                        if not any(
                            ".".join(tgt_parts[:i]) in targets
                            for i in range(1, len(tgt_parts) + 1)
                        ):
                            continue
                    edge_key = (func_id, method_id)
                    if edge_key not in existing_calls:
                        existing_calls.add(edge_key)
                        graph.add_edge(Edge(
                            source=func_id, target=method_id, kind=EdgeKind.CALLS,
                        ))


def _import_validated_candidates(
    candidates: list[tuple[str, str]],
    src_mod: str,
    module_ids: set[str],
    import_targets: dict[str, set[str]],
) -> list[tuple[str, str]]:
    """Filter property candidates to those whose class is imported by src_mod.

    When variable type is unknown (e.g. loop variables), this narrows the
    candidates using import validation.  Returns only candidates where the
    source module imports the target class's module.
    """
    targets = import_targets.get(src_mod, set())
    valid = []
    for class_id, method_id in candidates:
        tgt_mod = _module_of(method_id, module_ids)
        if src_mod == tgt_mod:
            valid.append((class_id, method_id))
            continue
        tgt_parts = class_id.split(".")
        if any(".".join(tgt_parts[:i]) in targets for i in range(1, len(tgt_parts) + 1)):
            valid.append((class_id, method_id))
    return valid


def _infer_variable_types(
    func_node: ast.FunctionDef | ast.AsyncFunctionDef,
) -> dict[str, str]:
    """Lightweight type inference for local variables within a function.

    Returns a mapping from variable name to the short class name, inferred from:
    - Constructor calls: ``x = ClassName(...)``
    - Type annotations: ``x: ClassName = ...`` or parameter ``x: ClassName``
    """
    var_types: dict[str, str] = {}

    # Parameter annotations
    for arg in func_node.args.args + func_node.args.kwonlyargs:
        if arg.annotation:
            ann_name = _resolve_name(arg.annotation)
            if ann_name:
                var_types[arg.arg] = ann_name.rsplit(".", 1)[-1]

    # Walk assignments in the function body
    for node in ast.walk(func_node):
        if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
            ann_name = _resolve_name(node.annotation)
            if ann_name:
                var_types[node.target.id] = ann_name.rsplit(".", 1)[-1]
        elif isinstance(node, ast.Assign) and len(node.targets) == 1:
            target = node.targets[0]
            if isinstance(target, ast.Name) and isinstance(node.value, ast.Call):
                # x = ClassName(...)
                call_name = _resolve_name(node.value.func)
                if call_name:
                    short = call_name.rsplit(".", 1)[-1]
                    # Only treat as constructor if name starts with uppercase
                    if short and short[0].isupper():
                        var_types[target.id] = short

    return var_types


def _find_func_id(
    tree: ast.Module,
    func_node: ast.FunctionDef | ast.AsyncFunctionDef,
    mod_id: str,
) -> str | None:
    """Determine the fully-qualified ID of a function node within a module."""
    # Check if it's a method inside a class
    for cls_node in ast.walk(tree):
        if not isinstance(cls_node, ast.ClassDef):
            continue
        for child in ast.iter_child_nodes(cls_node):
            if child is func_node:
                return f"{mod_id}.{cls_node.name}.{func_node.name}"
    # Top-level function
    for child in ast.iter_child_nodes(tree):
        if child is func_node:
            return f"{mod_id}.{func_node.name}"
    return None


