"""
Python source code parser.

Walks a Python codebase using the ast module and produces a CodeGraph
with nodes (modules, classes, functions) and edges (calls, imports,
inheritance, containment).

Call graph generation is delegated to PyCG (vendored), which performs
inter-procedural analysis with assignment tracking to resolve calls
including obj.method(), cross-module imports, and closures.
"""

from __future__ import annotations

import ast
import logging
import os
from pathlib import Path

from topo_parser.graph import CodeGraph, Edge, EdgeKind, Node, NodeKind

logger = logging.getLogger(__name__)


def parse_python_project(root: Path) -> CodeGraph:
    """
    Parse a Python project directory into a CodeGraph.

    Walks all .py files under `root`, extracts entities and relationships.
    Detects src-layout packages and uses the Python package root for module IDs.
    Call edges are generated by PyCG's inter-procedural analysis.
    """
    graph = CodeGraph()
    root = root.resolve()
    py_files = sorted(root.rglob("*.py"))

    # Detect Python package roots: directories containing __init__.py that
    # aren't nested inside another package. Handles both flat layout
    # (root/pkg/__init__.py) and src layout (root/src/pkg/__init__.py).
    package_roots = _find_package_roots(root, py_files)

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        _extract_from_file(graph, tree, py_file, pkg_root or root)

    # Use PyCG for call edges (inter-procedural analysis with type inference),
    # falling back to AST-based resolution if PyCG fails.
    pycg_calls = _extract_calls_pycg(root, py_files, package_roots)
    if pycg_calls is not None:
        _add_pycg_calls(graph, pycg_calls)
        # PyCG doesn't resolve super().method() — supplement with AST
        _add_super_calls_ast(graph, root, py_files, package_roots)
    else:
        _resolve_call_edges_ast(graph)

    # Resolve INHERITS edges (always AST-based)
    _resolve_inherits_edges(graph)
    return graph


def _find_package_roots(root: Path, py_files: list[Path]) -> list[Path]:
    """Find directories that serve as Python package roots.

    A package root is the parent of a top-level Python package. For example,
    in a src layout (proj/src/pkg/__init__.py), the package root is proj/src/.
    In a flat layout (proj/pkg/__init__.py), the package root is proj/.
    """
    # Find all directories containing __init__.py
    init_dirs: set[Path] = set()
    for f in py_files:
        if f.name == "__init__.py":
            init_dirs.add(f.parent.resolve())

    # A package root is the parent of a package dir whose parent is NOT itself a package.
    # This gives us the directory from which Python module IDs should be computed.
    package_roots: set[Path] = set()
    for pkg_dir in init_dirs:
        parent = pkg_dir.parent
        if parent not in init_dirs:
            package_roots.add(parent)

    return sorted(package_roots)


def _best_package_root(file: Path, package_roots: list[Path]) -> Path | None:
    """Find the most specific package root that contains this file."""
    file = file.resolve()
    best: Path | None = None
    for pr in package_roots:
        if file.is_relative_to(pr):
            if best is None or len(pr.parts) > len(best.parts):
                best = pr
    return best


def _module_id(file: Path, root: Path) -> str:
    """Derive a module id from file path relative to root."""
    rel = file.relative_to(root)
    parts = list(rel.with_suffix("").parts)
    if parts[-1] == "__init__":
        parts = parts[:-1]
    return ".".join(parts) if parts else rel.stem


def _extract_from_file(
    graph: CodeGraph, tree: ast.Module, file: Path, root: Path
) -> None:
    """Extract nodes and edges from a single parsed file."""
    mod_id = _module_id(file, root)

    # Module node
    graph.add_node(Node(id=mod_id, kind=NodeKind.MODULE, file=file, line=1, name=mod_id.split(".")[-1]))

    for node in ast.iter_child_nodes(tree):
        if isinstance(node, ast.ClassDef):
            _extract_class(graph, node, mod_id, file)
        elif isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, node, mod_id, file)
        elif isinstance(node, (ast.Import, ast.ImportFrom)):
            _extract_import(graph, node, mod_id)


def _extract_class(
    graph: CodeGraph, node: ast.ClassDef, parent_id: str, file: Path
) -> None:
    """Extract a class node, its methods, and inheritance edges."""
    class_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=class_id, kind=NodeKind.CLASS, file=file, line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=class_id, kind=EdgeKind.CONTAINS))

    # Inheritance (raw names, resolved later by _resolve_inherits_edges)
    for base in node.bases:
        base_name = _resolve_name(base)
        if base_name:
            graph.add_edge(Edge(source=class_id, target=base_name, kind=EdgeKind.INHERITS))

    # Methods
    for child in ast.iter_child_nodes(node):
        if isinstance(child, (ast.FunctionDef, ast.AsyncFunctionDef)):
            _extract_function(graph, child, class_id, file)


def _extract_function(
    graph: CodeGraph,
    node: ast.FunctionDef | ast.AsyncFunctionDef,
    parent_id: str,
    file: Path,
) -> None:
    """Extract a function/method node. Call edges are added by PyCG."""
    func_id = f"{parent_id}.{node.name}"
    graph.add_node(Node(id=func_id, kind=NodeKind.FUNCTION, file=file, line=node.lineno, name=node.name))
    graph.add_edge(Edge(source=parent_id, target=func_id, kind=EdgeKind.CONTAINS))


def _extract_import(graph: CodeGraph, node: ast.Import | ast.ImportFrom, mod_id: str) -> None:
    """Extract import edges.

    For `import foo.bar`, creates an edge to `foo.bar`.
    For `from foo.bar import baz, qux`, creates edges to both
    `foo.bar` (the module) and `foo.bar.baz`, `foo.bar.qux` (the names).
    This allows call resolution to map `baz()` -> `foo.bar.baz`.
    """
    if isinstance(node, ast.Import):
        for alias in node.names:
            graph.add_edge(Edge(source=mod_id, target=alias.name, kind=EdgeKind.IMPORTS))
    elif node.module:
        graph.add_edge(Edge(source=mod_id, target=node.module, kind=EdgeKind.IMPORTS))
        for alias in node.names:
            if alias.name != "*":
                qualified = f"{node.module}.{alias.name}"
                graph.add_edge(Edge(source=mod_id, target=qualified, kind=EdgeKind.IMPORTS))


## ---------------------------------------------------------------------------
## PyCG integration — inter-procedural call graph generation
## ---------------------------------------------------------------------------


def _extract_calls_pycg(
    root: Path, py_files: list[Path], package_roots: list[Path],
) -> dict[str, list[str]] | None:
    """Run PyCG on the project and return the call graph as {caller: [callees]}.

    Returns None if PyCG fails (the caller should fall back to AST resolution).
    """
    try:
        from topo_parser._vendor.pycg.pycg import CallGraphGenerator
    except ImportError:
        logger.debug("PyCG not available, falling back to AST resolution")
        return None

    # PyCG needs: entry_points (list of .py file paths), package (package dir)
    # It uses importlib hooks, so we need to chdir to the project root.
    entry_points = [str(f) for f in py_files]
    if not entry_points:
        return None

    # Determine the package directory for PyCG.
    # For src-layout: use the first package root (e.g., proj/src/)
    # For flat layout: use the project root
    # For standalone files: use the project root
    pkg_dir = str(package_roots[0]) if package_roots else str(root)

    old_cwd = os.getcwd()
    try:
        os.chdir(str(root))
        cg = CallGraphGenerator(entry_points, pkg_dir, -1, "call-graph")
        cg.analyze()
        raw = cg.output()
        # Normalize: convert sets to sorted lists
        result: dict[str, list[str]] = {}
        for caller, callees in raw.items():
            if isinstance(callees, set):
                result[caller] = sorted(callees)
            else:
                result[caller] = list(callees)
        return result
    except Exception:
        logger.debug("PyCG analysis failed, falling back to AST resolution", exc_info=True)
        return None
    finally:
        os.chdir(old_cwd)


def _add_pycg_calls(graph: CodeGraph, pycg_calls: dict[str, list[str]]) -> None:
    """Add CALLS edges from PyCG output, mapping to known graph nodes.

    PyCG produces fully-qualified names like 'pkg.module.Class.method'.
    We match these against our graph's node IDs and only add edges where
    both source and target are known nodes (to avoid phantom edges).
    """
    node_ids = set(graph.nodes)
    seen: set[tuple[str, str]] = set()

    for caller, callees in pycg_calls.items():
        # PyCG may use slightly different module IDs. Try exact match first.
        source = caller if caller in node_ids else None
        if source is None:
            continue
        for callee in callees:
            target = callee if callee in node_ids else None
            if target is None:
                continue
            edge_key = (source, target)
            if edge_key not in seen:
                seen.add(edge_key)
                graph.add_edge(Edge(source=source, target=target, kind=EdgeKind.CALLS))


def _add_super_calls_ast(
    graph: CodeGraph, root: Path, py_files: list[Path], package_roots: list[Path],
) -> None:
    """Supplement PyCG with AST-based super().method() resolution.

    PyCG resolves super() to <builtin>.super but doesn't follow through
    to the parent class method. We walk the AST to find super().method()
    patterns and resolve them using the declared base class.
    """
    node_ids = set(graph.nodes)
    existing_calls = {(e.source, e.target) for e in graph.edges_by_kind(EdgeKind.CALLS)}

    for py_file in py_files:
        try:
            source = py_file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(py_file))
        except (SyntaxError, UnicodeDecodeError):
            continue

        pkg_root = _best_package_root(py_file, package_roots)
        file_root = pkg_root or root
        mod_id = _module_id(py_file, file_root)

        for cls_node in ast.walk(tree):
            if not isinstance(cls_node, ast.ClassDef):
                continue
            class_id = f"{mod_id}.{cls_node.name}"
            if not cls_node.bases:
                continue
            base_name = _resolve_name(cls_node.bases[0])
            if not base_name:
                continue

            for method in ast.iter_child_nodes(cls_node):
                if not isinstance(method, (ast.FunctionDef, ast.AsyncFunctionDef)):
                    continue
                func_id = f"{class_id}.{method.name}"
                if func_id not in node_ids:
                    continue

                for child in ast.walk(method):
                    if not isinstance(child, ast.Call):
                        continue
                    if not (
                        isinstance(child.func, ast.Attribute)
                        and isinstance(child.func.value, ast.Call)
                        and isinstance(child.func.value.func, ast.Name)
                        and child.func.value.func.id == "super"
                    ):
                        continue
                    # super().method_name -> resolve to base class
                    method_name = child.func.attr
                    raw_target = f"{base_name}.{method_name}"
                    # Try to resolve the raw target to a known node
                    target = _try_resolve(func_id, raw_target, node_ids, {})
                    if target and (func_id, target) not in existing_calls:
                        existing_calls.add((func_id, target))
                        graph.add_edge(Edge(
                            source=func_id, target=target, kind=EdgeKind.CALLS,
                        ))


## ---------------------------------------------------------------------------
## AST-based call resolution (fallback when PyCG is unavailable)
## ---------------------------------------------------------------------------


def _self_param_name(node: ast.FunctionDef | ast.AsyncFunctionDef) -> str | None:
    """Return the name of the first parameter if it looks like self/cls."""
    if node.args.args:
        name = node.args.args[0].arg
        if name in ("self", "cls"):
            return name
    return None


def _resolve_call(
    node: ast.expr,
    self_name: str | None,
    class_id: str | None,
    base_name: str | None = None,
) -> str | None:
    """Resolve a call expression, with special handling for self/cls/super().

    For ``self.method()``, rewrites to ``ClassName.method`` so the
    downstream resolver can match it to a known node via ancestor prefix walk.
    For ``super().method()``, rewrites to ``BaseName.method`` using the
    first declared base class.
    """
    # self.method() or cls.method() -> ClassName.method
    if (
        self_name
        and class_id
        and isinstance(node, ast.Attribute)
        and isinstance(node.value, ast.Name)
        and node.value.id == self_name
    ):
        class_short = class_id.rsplit(".", 1)[-1]
        return f"{class_short}.{node.attr}"

    # super().method() -> BaseName.method
    if (
        class_id
        and isinstance(node, ast.Attribute)
        and isinstance(node.value, ast.Call)
        and isinstance(node.value.func, ast.Name)
        and node.value.func.id == "super"
    ):
        if base_name:
            return f"{base_name}.{node.attr}"
        return None

    return _resolve_name(node)


def _resolve_call_edges_ast(graph: CodeGraph) -> None:
    """AST-based fallback: extract and resolve call edges from function bodies.

    This is used when PyCG is unavailable. It re-parses each file to find
    call expressions and resolves them using ancestor prefix walking and
    import maps. Less precise than PyCG but requires no external dependency.
    """
    # Re-extract call edges from the AST
    for node_obj in list(graph.nodes.values()):
        if node_obj.kind != NodeKind.FUNCTION:
            continue
        try:
            source = node_obj.file.read_text(encoding="utf-8")
            tree = ast.parse(source, filename=str(node_obj.file))
        except (SyntaxError, UnicodeDecodeError):
            continue
        func_node = _find_ast_function(tree, node_obj.line, node_obj.name)
        if func_node is None:
            continue

        # Determine class context for self/cls/super resolution
        class_id, base_name = _find_class_context(tree, node_obj.id)
        self_name = _self_param_name(func_node) if class_id else None

        seen_calls: set[str] = set()
        for child in ast.walk(func_node):
            if isinstance(child, ast.Call):
                callee = _resolve_call(child.func, self_name, class_id, base_name)
                if callee and callee not in seen_calls:
                    seen_calls.add(callee)
                    graph.add_edge(Edge(
                        source=node_obj.id, target=callee, kind=EdgeKind.CALLS,
                    ))

    # Now resolve raw call targets to known nodes
    _resolve_raw_edges(graph, {EdgeKind.CALLS})


def _find_ast_function(
    tree: ast.Module, line: int, name: str,
) -> ast.FunctionDef | ast.AsyncFunctionDef | None:
    """Find a function/method AST node by line number and name."""
    for node in ast.walk(tree):
        if (
            isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))
            and node.name == name
            and node.lineno == line
        ):
            return node
    return None


def _find_class_context(
    tree: ast.Module, func_id: str,
) -> tuple[str | None, str | None]:
    """Determine the enclosing class ID and base class name for a function.

    Returns (class_id, base_name) or (None, None) if not a method.
    """
    parts = func_id.rsplit(".", 2)
    if len(parts) < 3:
        return None, None
    # Check if parent is a class by looking for it in the func_id
    # func_id format: "mod.Class.method" — parent would be "mod.Class"
    parent_id = func_id.rsplit(".", 1)[0]
    # Walk AST to find the class
    for node in ast.walk(tree):
        if isinstance(node, ast.ClassDef):
            # Check if this class name matches the parent
            if parent_id.endswith(f".{node.name}") or parent_id == node.name:
                base_name = None
                if node.bases:
                    base_name = _resolve_name(node.bases[0])
                return parent_id, base_name
    return None, None


def _resolve_name(node: ast.expr) -> str | None:
    """Best-effort resolve an AST expression to a dotted name string."""
    if isinstance(node, ast.Name):
        return node.id
    if isinstance(node, ast.Attribute):
        value = _resolve_name(node.value)
        if value:
            return f"{value}.{node.attr}"
    return None


def _resolve_inherits_edges(graph: CodeGraph) -> None:
    """Resolve raw targets in INHERITS edges to actual graph node IDs."""
    _resolve_raw_edges(graph, {EdgeKind.INHERITS})


def _resolve_raw_edges(graph: CodeGraph, kinds: set[EdgeKind]) -> None:
    """Resolve raw targets in edges of given kinds to actual graph node IDs.

    Raw edges have targets like 'helper' or 'Enum'. This pass replaces them
    with fully qualified node IDs where possible, and drops edges that can't
    be resolved to known nodes.
    """
    node_ids = set(graph.nodes)

    # Build import map: for each module, map imported short names to full targets.
    import_map: dict[str, dict[str, str]] = {}
    for edge in graph.edges_by_kind(EdgeKind.IMPORTS):
        mod = edge.source
        target = edge.target
        short = target.rsplit(".", 1)[-1]
        import_map.setdefault(mod, {})[short] = target

    keep: list[Edge] = []
    for edge in graph.edges:
        if edge.kind not in kinds:
            keep.append(edge)
            continue
        target = _try_resolve(edge.source, edge.target, node_ids, import_map)
        if target:
            keep.append(Edge(source=edge.source, target=target, kind=edge.kind))

    graph.edges = keep


def _try_resolve(
    source: str, raw_target: str, node_ids: set[str],
    import_map: dict[str, dict[str, str]],
) -> str | None:
    """Try to resolve a raw edge target to a known node ID."""
    # 1. Already a known node ID (fully qualified call)
    if raw_target in node_ids:
        return raw_target

    parts = source.split(".")

    # 2. Qualify with each ancestor prefix of the source
    # source="pkg.mod.Class.method", try "pkg.mod.Class.helper", "pkg.mod.helper", "pkg.helper"
    for i in range(len(parts) - 1, 0, -1):
        candidate = ".".join(parts[:i]) + "." + raw_target
        if candidate in node_ids:
            return candidate

    # 3. Handle dotted targets via imports: "EdgeKind.CALLS" where EdgeKind was imported
    first_part = raw_target.split(".")[0]
    rest = raw_target.split(".")[1:]
    for i in range(len(parts), 0, -1):
        mod_candidate = ".".join(parts[:i])
        if mod_candidate in import_map:
            if first_part in import_map[mod_candidate]:
                imported_target = import_map[mod_candidate][first_part]
                if rest:
                    full = imported_target + "." + ".".join(rest)
                else:
                    full = imported_target
                if full in node_ids:
                    return full

    return None
